# Generated by Django 4.1.7 on 2023-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronousShopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameters', models.CharField(max_length=100)),
                ('shoping_centers', models.CharField(max_length=100)),
                ('roads', models.CharField(max_length=100)),
                ('duration_time', models.IntegerField()),
            ],
        ),
    ]
